version: 2.1
orbs:
  node: circleci/node@7.2.0

jobs:
  build:
    # docker:
    #   - image: cimg/node:24.7.0
    # resource_class: medium
    macos:
      xcode: 16.4.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      # - run: sudo apt update && sudo apt install rsync
      - node/install-packages
      - run: npm run lint
      - run: npm run build:ci

workflows:
  build:
    jobs:
      - build
