version: 2.1
orbs:
  node: circleci/node@7.2.1

jobs:
  build:
    macos:
      xcode: 27.0
    resource_class: m4pro.medium
    steps:
      - checkout
      # - run: sudo apt update && sudo apt install rsync
      - node/install-packages
      - run: npm run lint
      - run: npm run build:ci

workflows:
  build:
    jobs:
      - build
